[package]
name = "usb-sound-player"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
udev = "0.7.0"
rodio = "0.17.1"
# libudev = "0.3"